### ISSUE TITLE
It does't work in goland

### ISSUE THREAD

**Issue by DestinyWang** [holgerbrandl/pasteimages#18]
I use `IntelliJ IDEA` and `GoLand`, it works fine with IntelliJ IDEA, but not with GoLand 

here is the versions:

## GoLand:
GoLand 2018.2.3
Build #GO-182.4505.32, built on September 20, 2018
Licensed to destiny

JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

## Markdown Navigator
2.6.0

## Paste Images into Markdown
1.2

**Comment by holgerbrandl** [comment]
What's the error?

**Comment by DestinyWang** [comment]
![image](https://user-images.githubusercontent.com/17758731/48404439-2d295300-e76b-11e8-8852-7e8cadc4a7e2.png)

Need the cooperation of other plugins? The plugins about markdown I use are just these two

**Comment by holgerbrandl** [comment]
The Markdown Navigator is using its own paste-handler which can also paste images. If you use MD Navigator anyway you may want to use it directly.

If you prefer to use this plugin, you'll need to disable the paste handler ![image](https://user-images.githubusercontent.com/200952/48406024-c6d50e00-e733-11e8-9b82-7eb9defd5afb.png)
