### ISSUE TITLE
Can you please add a License file to the project

### ISSUE THREAD

**Issue by vsch** [holgerbrandl/pasteimages#4]
@holgerbrandl, 

I am the author of Markdown Navigator plugin, which comes in two flavours: open source/free and [enhanced version](https://vladsch.com/products) which is commercially licensed.

I would like to add Paste image into my plugin that is more integrated with the plugin's Markdown Psi tree context and plugin's configuration settings. I considered using your image manipulation library but due to a lack of a LICENSE in the project cannot know what your policy is on re-use of your code.

BTW, Markdown Navigator has a ton of productivity features for Markdown over and above preview rendering that Markdown Support offers, such as rename refactoring, two way HTML/Markdown conversion, GitHub Wiki support, error and warning annotations, auto formatting, wrap on typing, completions of links, anchor refs, footnotes; HTML to Markdown conversion, HTML export, PDF export, etc. It also has some Jekyll support for mapping relative links which allows refactoring and completions to work in Jekyll projects.

I am offering a free license to all plugin developers.  If you have not tried it yet you can get a [trial license](https://vladsch.com/product/markdown-navigator/try). If you find it to your liking just sent me an e-mail (on my [GitHub profile](https://github.com/vsch)) and I will issue your license.

**Comment by vsch** [comment]
@holgerbrandl, thank you.

**Comment by holgerbrandl** [comment]
You're welcome @vsch. I hope the license is open enough for your usecase. Nice project btw, although I'd imagine it's hard to compete with the free JB Markdown plugin, that covers even some of your paid-only features.

**Comment by vsch** [comment]
@holgerbrandl, the license is compatible with both the open and commercial version of the plugin. Thank you.

Markdown Support actually does not have the full set of free Markdown Navigator features, including GitHub accurate preview. The hardest part to compete with is the perception that being a "JetBrains" official plugin it must be better in features or support, which is not generally true in this case. 

I really recommend you give Markdown Navigator a try. I think that once you get used to the completions, refactoring, formatting and wrap on typing you will wonder how you ever worked in markdown without it. Your plugin works fine in Markdown Navigator. What I want is to add automatic detection when clipboard contains an image so regular paste will paste a link and save the file without needing a separate shortcut. Once I figure out how to do this reliably, I will PR the changes to your plugin. I also want to have the ability to put the caret on an image link element so pasting an image will replace the link or the file with clipboard contained image. I found when using your plugin a large percentage of the time I wanted to update an image with a new screenshot and not having defaults taken from the link was a distraction that could be avoided.

BTW, [Valentin Fondaratov](https://github.com/valich) is the developer of Markdown Support on his own effort not a JetBrains project. Last we touched base he was on the RubyMine dev team. Being part of the JetBrains team he does have more insight into the API and upcoming changes. 

However, I learned to get insight into upcoming API changes through daily builds of the https://github.com/JetBrains/intellij-community master branch and use it as my "dev" IDE with builds on latest released version to make sure I don't get ahead of the API for old releases, which has happened on occasion.

Conversion rate was good on new version upgrades because of the balloon notification listing new features added. However, JetBrains changed the balloons to just a sliver from the full balloon and that has seriously affected conversion rate. They also added a pop-up when both Markdown Navigator and Markdown Support are installed letting the user select one of them to avoid the conflict. The default selection is Markdown Support, being a JetBrains official plugin and the default selection probably has an effect. With all the perceived disadvantages my plugin is still leading in downloads and it was released later than Markdown Support.

To be frank, licensing wasn't making the effort financially justifiable as a full time job before the change but looked promising. Since the change to tiny balloons it became ridiculous. It is not dissatisfaction but lack of awareness of how much more productive it is to have full IDE support for Markdown. In general, feedback from licensed users is "getting the license is the best decision they made and best money they spent".

It would be great if JetBrains had more support for plugin developers to make some financial rewards for their efforts. I find that I would have a hard time using the IDE without having some crucial third party plugins but I have seen a lot of good plugins abandoned because the maintenance effort is significant and beyond the initial challenge of building the plugin there is no incentive to keep at it.

Then again, "If life was like that, then you wouldn't need VISA". 😁

**Comment by holgerbrandl** [comment]
Thanks Vladimir for your insights.

> your plugin
I've tried and here are some first impressions
Pros
* overall usage very smooth and similar to JB plugin

Cons
* no structure view popup with sections etc (the JB plugin has this since recently thanks to a [PR(https://github.com/JetBrains/intellij-plugins/pull/474))
* I could not find a way to show just the preview (not sure if all these HTML preview modes are so helpful)
* most of the bars on top of the editor were disabled (paid only??)
* code chunk language injection just paid-only
* code chunks require leading empty line for correct parsing

Also none of the features I miss in the JB plugin seem to be present in Markdown Navigator. See
https://github.com/holgerbrandl/r4intellij/blob/master/misc/todo.md#markdown-impro-wishlist

> Valentin Fondaratov's plugin
Since the jb markdown plugin belongs to https://github.com/JetBrains/intellij-plugins it feels very affiliated to JB to me. It's also listed as JB plugin in the plugin-manager. So it looks like more than his "hobby"

> conflicting plugins
I was a bit more lucky. Recently JB indicated to me that they might drop their own R plugin in favor of mine (https://github.com/holgerbrandl/r4intellij).

> financial incentives
I totally agree about the last paragraph. JB could/should support plugin-devs better. Especially those ones that provide free/open-source plugins.

**Comment by vsch** [comment]
@holgerbrandl, yes most of the enhanced features require a license, please get one at https://vladsch.com/product/markdown-navigator/try. If you like the features I offer a free license to all plugin developers. 

The plugin started as completely open source but when I decided to devote full time to it I had to make a decision. I tried the donations route but it yielded 2 donations after a month. I had to give an incentive to license. 

I did not imply that Markdown Support is a hobby but there is no one on it full time, other than Valentin who is tasked with other work.

On specific features:

> * no structure view popup with sections etc (the JB plugin has this since recently thanks to a [PR(https://github.com/JetBrains/intellij-plugins/pull/474))

A licensed feature. Structure view has several sections. Headers shows header hierarchy. Document section shows elements in document order:

![Issue_4_image](https://github.com/vsch/idea-multimarkdown/raw/master/assets/doc/GitHub/Issue_4_image.png)      

> * I could not find a way to show just the preview (not sure if all these HTML preview modes are so helpful)

Use the right hand part of the toolbar and click preview only ![Icons Layout Preview Only](https://github.com/vsch/idea-multimarkdown/raw/master/resources/icons/layout/Preview_only%402x.png) 

> * most of the bars on top of the editor were disabled (paid only??)

Yes, requires a license. The unlicensed versions does not have a full Markdown Psi Tree that most of the features require. You can hide disabled toolbar buttons in settings:

![Screen Shot Settings Hide Toolbar Buttons](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_HideToolbarButtons.png) 

* code chunk language injection just paid-only

Yes, requires a license. Also HTML blocks and Jekyll front-matter automatically inject language unless disabled in options.

> * code chunks require leading empty line for correct parsing
 
I tried it and could not duplicate if you could give an example of where it fails to parse it would be very much appreciated because it would be a bug. 

From your **Markdown impro wishlist** link:

> * Click to to jump to code

Not sure what you mean by jump to code?

> * synced scrolling
> * aligned cursor with preview
> * synced caret http://codepen.io/ArtemGordinsky/pen/GnLBq

No synced scrolling but have editor caret to Preview sync and in licensed version clicking on preview will move editor caret to line in source containing the element. Also have preview element highlight on editor caret movement:  

![Preview Scroll To With Highlight](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/noload/PreviewScrollToWithHighlight.gif) 

> * make sure that https://youtrack.jetbrains.com/issue/RUBY-19204 is being fixed or fix it

Tried it and it works in Markdown Navigator (with license) here is the result:

    # some section 
    
    bla bla bla 
    
    ```groovy 
    foo = $/a*b/$ 
    ```

> * highlight search results in preview
>   * http://stackoverflow.com/questions/19418626/javafx-search-and-highlight-text-add-search-bar-for-loaded-web-page
> * search in preview

Not done but can be added. No one asked for these features before.

* intention to unify header styles (see [RUBY-19093](https://youtrack.jetbrains.com/issue/RUBY-19093))

Have intentions to change header style between ATX and SETEXT and to change whether ATX has trailing `#`'s and match these to leading number of `#` in Code Style > Markdown options

> * line comment/uncomment see http://stackoverflow.com/questions/4823468/comments-in-markdown. Examples:
>
>   [//]: <> (seems more generic) [//]: <> (seems more generic)

Can be easily added. Right now line comment mode will wrap the line in `<!-- -->`

**Comment by holgerbrandl** [comment]
That's an impressive feature set. Especially the "preview element highlight on editor caret movement" which referred to as "synced caret".

You might want to emphasize more what's possible by getting the pro version. Like my issue with the disabled buttons: it was simply not clear at all to me that this is paid-only, it looked more broken or context-dependent. Same with the intentions, they should be there but show a dialog instead of applying the quickfix. This imho would make users more aware of the benefits of the full version.

 For sure having an option to hide all paid-features (as it seems to be possible to some extent already) is also nice (and free-edition-user-friendly), but first I would educate (i.e. spam with dialog-boxes and dummy quickfixes) users more about the differences between both editions.

**Comment by vsch** [comment]
@holgerbrandl, thank you for the good advice. I have been thinking of adding my own dialog after a fresh install to outline differences since the notification balloons have closed that option.

Please get a free trial license so I can convert it for you to a full license. Once you get used to all the features of the enhanced version you will wonder how you worked without it.

Plus the implementation of user suggestions is very active and you have a different perspective than other users of the plugin. I would love to have your suggestions on improving the functionality to make it more comfortable for your use cases. Last few releases I completed the user wish list and now I am ready for more.

**Comment by holgerbrandl** [comment]
Not sure how to report issues/feedback, so here we go:

0. I love the section view.

1. when adding new content, the preview should change/scroll to the corresponding section. Currently users seem to have to sync both views manually before seeing changes in the preview. See JB MD plugin, for a more streamlined approach.

2. The button bar is not shown at all on my 15 inc retina macbook, but rather an empty bar is shown. See https://snag.gy/eD4orN.jpg

3. The pdf export does not work for me. UI comes up but when I click "OK" nothing happens.

**Comment by vsch** [comment]
@holgerbrandl, you can report Issues at https://github.com/vsch/idea-multimarkdown/issues

>1. when adding new content, the preview should change/scroll to the corresponding section. Currently users seem to have to sync both views manually before seeing changes in the preview. See JB MD plugin, for a more streamlined approach.

What do you mean by sync both views manually? The preview updates on document changes and if you select the `Highlight on typing` it will also highlight the line/block as you type. I tend to find this distracting while typing but it is there as an option. 

I have noticed that after adding a license sometimes currently open files don't update as expected, including highlighting. Closing file and re-opening it fixes the issue. I am still trying to figure out under what conditions this occurs. Could be this issue.

![screenshot_settings_previewsourcesynchronization](https://cloud.githubusercontent.com/assets/10299086/23436176/8d0915e6-fdd7-11e6-9532-e247d66c92a2.png)

There is also an option to tweak the delay between typing and preview update: `Typing update delay`, default is 300ms. Longer gives better typing response in large files (>2000 lines and >100k), shorter faster preview updates.

![screenshot_main_licensed](https://cloud.githubusercontent.com/assets/10299086/23436413/704b277c-fdd8-11e6-846f-37e7decc7544.png)


2. The `Hide disabled toolbar buttons` should be selected on 15" screens because when the toolbar does not fit the IDE changes it to a single `>>` button which pops out the toolbar. If disabled buttons are hidden then the toolbar will be short enough to fit the screen. I have been meaning to add settings that would allow the user to hide buttons they never use. I will address this. Not using a laptop I am oblivious to smaller screen issues.

3. What OS are you running on? Usually anything to do with files winds up being un-addressed OS differences. I will test it some more.

BTW, I upgraded your license to a full license. When it is re-activated on next plugin install it will show the correct expiration. Alternately you can remove the license and load license from server to have the plugin fetch it instead of needing the license code.

**Comment by holgerbrandl** [comment]
Great, I'll use the tracker for new requests.

Indeed `Highlight on typing` solves the problem and I don't see why it's not enabled by default. I guess most users will miss it.

Concerning the toolbar. The better fix would be to show as much as possible and ignore the rightmost icons if they don't fit. Idea itself does in such a way:
![image](https://cloud.githubusercontent.com/assets/200952/23453378/6d0e56fc-fe68-11e6-89e3-05d42dac764b.png)

I'm using MacOS Sierra 10.12.3

Thanks for the license. I will start using it and most likely stick to it given it's nice feature set and your excellent support.
