### ISSUE TITLE
Crash after paste

### ISSUE THREAD

**Issue by grafmouse** [holgerbrandl/pasteimages#40]

**Comment by grafmouse** [comment]
Plugin version: 1.2.4
IDE Version: PhpStorm 2022.2.3, Build #PS-222.4345.15, built on October 5, 2022

Step to reproduce:
- Copy image to clipboard
- Press cmd+v to paste image into markdown document
- Update Directory Name (plugin doesn't remember last value)
- Confirm (close dialog)

Expected behavior:
Image pasted into markdown document without errors.

Current behavior:
The image is pasted correctly into the markdown document, but errors occurred.

[stacktrace.txt](https://github.com/holgerbrandl/pasteimages/files/9956413/stacktrace.txt)
[threadDump.txt](https://github.com/holgerbrandl/pasteimages/files/9956414/threadDump.txt)

**Comment by holgerbrandl** [comment]
Can't reproduce. Feel welcome to reopen if needed.
