### ISSUE TITLE
Drag&Drop functionality in IntelliJIdea is broken due to the plugin "Paste Image To Markdown" 

### ISSUE THREAD

**Issue by Morons** [holgerbrandl/pasteimages#41]
**Please refer to the jetbrains issue below.**
This makes pasteimages 100% broken!  I cannot use it until it is fixed as it is more importent to be able to Drag and Drop selected Code around in my projects!

[Drag&Drop functionality in the editor is broken due to the plugin "Paste Image To Markdown" ](https://youtrack.jetbrains.com/issue/MP-4715/DragDrop-functionality-in-the-editor-is-broken-due-to-the-plugin-Paste-Image-To-Markdown)

**Comment by holgerbrandl** [comment]
Thanks for reporting. I've replied in youtrack. Not sure how to how to reproduce the problem.
