### ISSUE TITLE
can't work in pycharm

### ISSUE THREAD

**Issue by mqinbin** [holgerbrandl/pasteimages#7]
I installed pycharm. and markdown-support plugin, and this plugin.

but this plugin does not work. in plugins the icon looks different with outhers.

below is my pycharm version:
--------------------------------------
PyCharm Community Edition 2016.3.3
Build #PC-163.15188.4, built on March 11, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

below is my markdown support version:
--------------------------------------
version 2016.3.20170209

below is my pycharm version:
--------------------------------------
version 1.1

**Comment by holgerbrandl** [comment]
The plugin was not yet flagged to be compatible with pycharm. This is fixed now.

It may take a day or two until Jetbrains has accepted the updated version. Once this has happened you can install it via the plugin manager within PyCharm.

**Comment by mqinbin** [comment]
that's great, thanks for your work!
